# developer/Dockerfile
FROM ubuntu:24.04

# Configurar entorno no interactivo
ENV DEBIAN_FRONTEND=noninteractive

# Instalar TODAS las dependencias
RUN apt-get update && apt-get install -y \
    gnupg \
    xfce4 \
    xfce4-goodies \
    tightvncserver \
    dbus-x11 \
    xfonts-base \
    libgl1-mesa-dri \
    x11-xkb-utils \
    openssh-server \
    postgresql-client \
    wget \
    sudo \
    python3 \
    python3-pip \
    python3-venv \
    git \
    nano \
    curl \
    net-tools 

# Configurar entorno virtual Python
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Instalar Flask y dependencias
RUN pip install flask psycopg2-binary


# Crear usuario developer
RUN useradd -m -s /bin/bash developer \
    && echo "developer:@ITB2024" | chpasswd \
    && usermod -aG sudo developer \
    && echo "developer ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# Configuración de VNC
USER developer
RUN mkdir -p /home/developer/.vnc
RUN echo "@ITB2024" | vncpasswd -f > /home/developer/.vnc/passwd && chmod 600 /home/developer/.vnc/passwd

# Configuración de XFCE para VNC
RUN echo "xrdb $HOME/.Xresources\nstartxfce4 &" > /home/developer/.vnc/xstartup && chmod +x /home/developer/.vnc/xstartup

## vscode stuff
USER root
RUN curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg \
  && mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg \
  && sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'

## Install vscode in the specifc version
RUN apt-get update && apt-get install -y code=1.88.1-1712771838 \
  && apt-get install -f

RUN cp /usr/lib/x86_64-linux-gnu/libxcb.so.1 /usr/share/code/ \
  && cp /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0 /usr/share/code/ \
  && sed -i 's/BIG-REQUESTS/_IG-REQUESTS/' /usr/share/code/libxcb.so.1 \
  && sed -i 's/BIG-REQUESTS/_IG-REQUESTS/' /usr/share/code/libxcb.so.1.1.0
RUN apt-get install xdg-utils --fix-missing -y

# Script de inicio
USER root
COPY startup.sh /startup.sh
RUN chmod +x /startup.sh

# Limpiar cache
RUN apt-get clean \
    && rm -rf /var/lib/apt/lists/*

#Exponer puertos necesarios
EXPOSE 1222 5901

CMD ["/bin/bash","/startup.sh"]
